### ISSUE TITLE
Building behind a proxy

### ISSUE THREAD

**Issue by toddinpal** [ottomatica/slim#134]
I can't find a way to build images when operating behind a proxy.  I can manually build a Docker image if I pass in the --build-arg http_proxy=http://www.foo.bar:80/ to the Docker build command.  How can I perform slim builds behind a proxy?

-tl

**Comment by chrisparnin** [comment]
If you edit the info.yml that is in the same directory as the Dockerfile, you can add arguments that get passed to docker as build arguments:

```yaml
description: My image
base_args:
  HTTP_PROXY: http://10.20.30.2:1234
```

Another option is to configure docker (edit ~/.docker/config.json) so that it uses your HTTP_PROXY.
https://docs.docker.com/network/proxy/

```json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://127.0.0.1:3001",
     "httpsProxy": "http://127.0.0.1:3001",
     "noProxy": "*.test.example.com,.example2.com"
   }
 }
}
```

Let me know if either of those approaches seems reasonable.

**Comment by toddinpal** [comment]
I had already set up a proxy in /etc/systemd/system/docker.service.d/http-proxy.conf 
However, now it doesn't look like I get even that far:
$ slim build images/alpine3.9-simple
building docker image
Step 1/27 : FROM alpine:3.9.4 AS openrc
net.js:708
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at WriteStream.Socket.write (net.js:708:11)
    at docker.modem.followProgress.ev (/home/tlittle/slim/lib/build.js:55:34)
    at processLine (/home/tlittle/slim/node_modules/docker-modem/lib/modem.js:404:11)
    at pump (/home/tlittle/slim/node_modules/docker-modem/lib/modem.js:393:9)
    at IncomingMessage.onStreamEvent (/home/tlittle/slim/node_modules/docker-modem/lib/modem.js:384:5)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)

**Comment by chrisparnin** [comment]
One possibility is that [dockerode](https://github.com/apocas/dockerode)'s connection is configured such that it isn't respecting proxy.

The failure is occurring [here](https://github.com/ottomatica/slim/blob/master/lib/build.js#L52), when the docker daemon isn't returning any data...

It might be helpful to quickly check if you can use the "info.yml" approach, since that would match your manual --build-arg approach.... you also need to ensure you are on the latest version that contains this patch:

https://github.com/ottomatica/slim/pull/112

**Comment by toddinpal** [comment]
Well my problems appear to be more fundamental now.  I've removed all the proxy stuff from docker and anywhere else I could find, and just done a fresh git clone, npm install, npm link.  And I'm still getting the same error.  Here is the output from "docker info":
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.1-ol
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc version: 4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.35-1902.302.2.el7uek.x86_64
 Operating System: Oracle Linux Server 7.8
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.779GiB
 Name: xxxxxxxx
 ID: JY77:CXI5:H6G4:QTKG:UFKQ:EYDH:QNLB:2V4P:2PE7:DC6I:JJ62:2ANJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries:

**Comment by chrisparnin** [comment]
Alright.

Did you try adding info.yml?

**Comment by toddinpal** [comment]
I did, but somewhere along the way, the problem became the dockerode problem.  I cleaned up everything, removed all proxy references I could find, and and now I get: 
$ slim build images/alpine3.9-simple/
building docker image
Step 1/27 : FROM alpine:3.9.4 AS openrc
 ---> 055936d39205
Step 2/27 : RUN mkdir -p /lib/apk/db /run
 ---> Using cache
 ---> 08b3a8124f5e
Step 3/27 : RUN apk add --no-cache --initdb openrc
 ---> Using cache
 ---> d8187fa0acbe
net.js:708
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at WriteStream.Socket.write (net.js:708:11)
    at docker.modem.followProgress.ev (/home/tlittle/slim/lib/build.js:55:34)
    at processLine (/home/tlittle/slim/node_modules/docker-modem/lib/modem.js:404:11)
    at pump (/home/tlittle/slim/node_modules/docker-modem/lib/modem.js:393:9)
    at IncomingMessage.onStreamEvent (/home/tlittle/slim/node_modules/docker-modem/lib/modem.js:384:5)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)

**Comment by chrisparnin** [comment]
This is sort of promising... you were able to at least do some network stuff such as fetch the image.  

Perhaps a simple guard against empty data being sent might be enough to over come any intermittent issues.

**Comment by chrisparnin** [comment]
I've added the guard here: https://github.com/ottomatica/slim/commit/96ac411b76ac6a4155fb111193b51e0eb82b5608

Does this help get past this step?

**Comment by toddinpal** [comment]
Yup!  Thanks!
