### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by darribas** [ottomatica/slim#147]
Here is the `Dockerfile` I'm using:

```Dockerfile
FROM darribas/gds_py:4.1
````
And the `info.yml` I'm including:

```yml
description: A containerised (Python) platform for Geographic Data Science
```

I'm getting the following error:

```shell
dani@homepod:~/code/gds_env/virtualbox$ slim build ./
building docker image
Step 1/1 : FROM darribas/gds_py:4.1
 ---> 654de8c9ff7a
[Warning] One or more build-args [SSHPUBKEY PKGS] were not consumed
Successfully built 654de8c9ff7a
Successfully tagged slim-vm:latest
exporting docker filesystem
creating initrd
Error: ENOENT: no such file or directory, stat '/home/dani/.slim/slim-vm/vmlinuz'
dani@homepod:~/code/gds_env/virtualbox$ 
```

Am I doing something wrong? (complete newbie here)

**Comment by chrisparnin** [comment]
> Error: ENOENT: no such file or directory, stat '/home/dani/.slim/slim-vm/vmlinuz'

Slim needs a kernel to package with the Docker container filesystem.

For example, in the alpine image, we do this:

```
FROM alpine:3.9.4 AS kernel
RUN mkdir -p /lib/apk/db /run
RUN apk add --no-cache --initdb linux-virt virtualbox-guest-modules-virt

# Need virtio modules for networking
COPY --from=kernel /lib/modules /lib/modules

# Copy kernel for later use
COPY --from=kernel /boot/vmlinuz-virt /vmlinuz
```

You'd need to add a basic linux kernel and leave on /vmlinuz.

You'd likely need an init program as well.

You might find the ubuntu image useful for doing this:
https://github.com/ottomatica/slim-images/blob/master/ubuntu16.04-simple/Dockerfile

**Comment by darribas** [comment]
Thank you very much for the quick response and the pointer!!!

If I get it correctly, an Ubuntu image with those extra installs should work. The container I want to convert into a VM is based on Ubuntu 18.04 I believe, so I might be lucky enough? Everything else it contains relates to a Data Science stack as far as I know.

A(n un)related question, feel free to disregard: this container, when `docker run`, launches a Jupyter server. Would the resulting image do that as well when launched, say, from VirtualBox? Ideally what I want, is a VM that I can click on VB and it'll launch the server so one can access it through the host browser. All locally.

Thank you very much again and congratulations on a really slick package!

**Comment by darribas** [comment]
I'll post here in case this helps other folks:

- Building from the suggested file, but starting with my original container (example [here](https://github.com/darribas/gds_env/blob/62cf40da3fd68d2c2ef79c768933aeeab06ab0e4/virtualbox/Dockerfile)) seems to work as in that it results in a final "success" build.
- However, I am not sure this allows me to do what I wanted (which is related to my misunderstanding of this project I think), that is to build a VirtualBox VM that I could export in a `.ova` file with everything that is required. When I export, the resulting file is about 8Kb, so clearly not including the container.

For this, I think this is not going to solve what I wanted to accomplish, but this is not a flaw of `slim` but my own misunderstanding. Thus, happy to close the issue.

Thank you very much again for the quick support!

**Comment by chrisparnin** [comment]
Trying to run, actually looks like there might be a silent error during build docker process... it never finishes the first step (pulling) for me...

```
$ slim build .
building docker image
Step 1/19 : FROM darribas/gds_py:4.1 AS kernel
exporting docker filesystem
creating initrd
building iso
Size of boot image is 4 sectors -> No emulation
 21.01% done, estimate finish Thu Jun 18 07:53:25 2020
 41.93% done, estimate finish Thu Jun 18 07:53:25 2020
 62.98% done, estimate finish Thu Jun 18 07:53:25 2020
 83.89% done, estimate finish Thu Jun 18 07:53:25 2020
Total translation table size: 2048
Total rockridge attributes bytes: 1193
Total directory bytes: 4096
Path table size(bytes): 38
Max brk space used 0
23868 extents written (46 MB)
cleaning up...
success!
```

Looking at the large size of the underlying image, I think there are a couple of limitations you'd run into using `slim`, which was primarily designed for smaller images, where as this looks like it would at least be 10 GB.

You might have better success with using packer. We have an example where we build an image using that here:

https://github.com/CSC-DevOps/Images/tree/master/Jenkins

**Comment by chrisparnin** [comment]
Yep, simply running `docker pull darribas/gds_py:4.1` was too big to unpack on my system:

```
...
76aa6604723f: Extracting  812.1MB/812.1MB
cf0081f608ef: Download complete 
0e4eafb7dabd: Download complete 
e0c5e91bab35: Download complete 
9eb5e34b0daa: Download complete 
failed to register layer: Error processing tar file(exit status 1): write /usr/share/inkscape/tutorials/tutorial-advanced.nl.svg: no space left on device
```
