### ISSUE TITLE
SSH key copy should use absolute paths

### ISSUE THREAD

**Issue by gjabell** [ottomatica/slim#3]
https://github.com/ottomatica/slim/blob/ce330cee1720fc1bf2d335b518d1d3f4297734ad/lib/env.js#L21

Slim command fails unless you are in the `script/keys` directory. Not sure how best to resolve the path in Node, guess it should be in relation to the project directory?

**Comment by ssmirr** [comment]
https://github.com/ottomatica/slim/commit/97e688b8ca079614706ade8e4666cb54a128ca0b should fix it. Could you check if it works now?

**Comment by gjabell** [comment]
Great! That works for me
