### ISSUE TITLE
How to stop a VM?

### ISSUE THREAD

**Issue by blissdev** [ottomatica/slim#42]
Currently, there is documentation such that you can build a VM, and run a VM, and delete a VM but it's not obvious to me how to stop a VM?

**Comment by chrisparnin** [comment]
Pushed patch to include new `stop` command. Can use like this:

```
slim stop micro1
```

Longer term, we're slowly building up abstractions in a library for what we call, 'virtual CRUD', making it easier to do this type of interactions with various VM providers.

**Comment by blissdev** [comment]
Very cool, thanks!
