### ISSUE TITLE
slim on AWS EC2

### ISSUE THREAD

**Issue by unixfox** [ottomatica/slim#51]
Hello,

I'm trying to boot an image from slim on AWS EC2 but I'm unable to make it work:
![slimaws](https://user-images.githubusercontent.com/4016501/62930187-774b6d80-bdab-11e9-9d14-9fe49bfdd0ed.jpeg)

Here what I did to convert an image from slim to an AMI:
1. `slim build images/alpine3.8-simple -f qcow2 -p kvm`
2. `cd ~/.slim/registry/alpine3.8-simple`
3. `qemu-img convert slim.qcow2 slim.raw`
4. `aws s3 cp slim.raw s3://slimiso`
5. `aws ec2 import-snapshot --description "slim image" --disk-container file://container.json`
6. Create an AMI from the imported snapshot:
![2019-08-13_11-22](https://user-images.githubusercontent.com/4016501/62930428-eaed7a80-bdab-11e9-9024-97b78fe45552.png)
7. Launch an EC2 instance from the AMI created previously.

Can someone help me to make an image from slim booting properly on AWS EC2?

**Comment by chrisparnin** [comment]
Booting on a cloud provider is completely untested!

However, I do think it is very interesting to investigate this.

**Comment by unixfox** [comment]
Hello, thank you for your reply!

It is indeed interesting to try to make slim working for AWS because that would allow some great possibilities for the cloud like creating small AMI that would be used for microservice.

My current use case of slim is to quickly launch a Minecraft server on AWS EC2.

**Comment by unixfox** [comment]
@chrisparnin According to the alpine wiki to boot on AWS we just need to install a bootloader: https://wiki.alpinelinux.org/wiki/Install_Alpine_on_Amazon_EC2#EBS_Backed_HVM_AMI
Would this be feasible to do on slim? If so how would I do that?

**Comment by unixfox** [comment]
Quick update. I managed to boot slim on AWS but it crashed due to a kernel panic.
I manually installed the bootloader using this method: https://wiki.archlinux.org/index.php/Syslinux#Manual_install and I used this syslinux configuration: https://github.com/ottomatica/slim/blob/master/scripts/syslinux/isolinux.cfg

The error is that it doesn't find the root filesystem:
![](https://i.imgur.com/BXQanfz.png)

**Comment by unixfox** [comment]
Ok I don't know how I got it working... it's unbelievable:
![](https://i.imgur.com/7iS3bWW.png)

I literally did some hacky stuff to get that working.
I had to launch an AMI from [linuxkit](https://github.com/linuxkit/linuxkit), then mounting the filesystem of that AMI to another EC2/VPS, after that I replaced the files `vmlinuz` and `initrd` (from linuxkit) with the files generated by slim: `slim build images/alpine3.8-simple -p kvm`.

**Comment by chrisparnin** [comment]
Amazing! This should help identify what's the delta needed on the images to make them ami-bootable.

There is a big software engineering conference deadline coming up this Friday, but we'll be able to dig into this more after that.

**Comment by unixfox** [comment]
No problem, I'm not here to urge you to add the AWS support for slim. I just wanted to see if I would be able to use slim on AWS in the future for my current project or if I would have to fallback to linuxkit.

About the real magic to make slim booting on AWS here is the content of the AMI:
```
[root@ip-172-31-3-6 slim]# ls -l
total 80940
-rw------- 1 root root 70188570 Apr 18  2017 initrd.img
-rw------- 1 root root  8029056 Apr 18  2017 kernel
-r--r--r-- 1 root root   116092 Aug 18 18:48 ldlinux.c32
-r--r--r-- 1 root root    69632 Aug 18 18:48 ldlinux.sys
drwx------ 2 root root    16384 Aug 18 18:48 lost+found
-rw-r--r-- 1 root root       93 Aug 18 18:48 syslinux.cfg
```
Note: initrd.img is the same type as the initrd of slim. And kernel is the same type as the vmlinuz of slim.

Here is the content of the `syslinux.cfg` file:
```
DEFAULT linux
LABEL linux
    KERNEL /kernel
    INITRD /initrd.img
    APPEND console=ttyS0
```

I uploaded here the content of the two other file:
[ldlinux.c32.zip](https://github.com/ottomatica/slim/files/3514974/ldlinux.c32.zip)
[ldlinux.sys.zip](https://github.com/ottomatica/slim/files/3514975/ldlinux.sys.zip)

I think most of the magic that linuxkit does to render a ramdisk bootable as an AMI is here: https://github.com/linuxkit/linuxkit/blob/master/src/cmd/linuxkit/moby/output.go
