### ISSUE TITLE
Attach command

### ISSUE THREAD

**Issue by mprey** [ottomatica/slim#70]
Hello,

I am a student at UT Austin in a virtualization class and I was looking to contribute to this project. After using this for a bit, having to C+P the ssh every time to connect to the micro-vm seemed redundant. I was wondering if I could create a `slim attach` command that would automatically try and connect to the most recent micro-vm provisioned. Alternatively, there could be an additional flag in `slim build` that would auto-attach to the VM after creation.

What do you think?

EDIT: Adding health checking with this ticket too. Details in PR #73

**Comment by chrisparnin** [comment]
The proposed `slim attach` command would be reasonable. 

Providing an optional vm-name: `slim attach [vm-name]` would allow you to connect to other instances.

**Comment by mprey** [comment]
That sounds great.

In the original post, the flag to auto-attach was supposed to be with `run` not `build`, what do you think of this?

**Comment by chrisparnin** [comment]
yes, auto-attach would make more sense on `run`.
