### ISSUE TITLE
Add `slim start [vm-name]` command

### ISSUE THREAD

**Issue by ssmirr** [ottomatica/slim#72]
Add a command to start an existing vm. 

#### Suggestion:
Implementation could use this for virtualbox provider: https://github.com/ottomatica/slim/blob/bf53f255a435bd6311cdbc91db0d42342fb11bd0/lib/providers/virtualbox.js#L94

This probably can be a modified version of `run` command, with the difference of not accepting any modification to the vm.

**Comment by mprey** [comment]
Could you explain this further? Does this command imply the VM you are trying to start is in a shutdown state in some way?

**Comment by ssmirr** [comment]
Yes, there is a `slim stop [vm-name]` command that can stop vms, also they may be stopped as a result of system restart etc.
