### ISSUE TITLE
Providing acpid support for KVM

### ISSUE THREAD

**Issue by mprey** [ottomatica/slim#75]
Currently, it seems only VirtualBox provides any remote support for acpid actions. Hyperkit only responds to killing its PID, but KVM has some potential here. The current KVM VM's will completely ignore any reboot or shutdown request and only respond to destroy. This leads to things such as `slim start` and `slim stop` practically being useless except for VirtualBox.

What do you think about adding support for ACPID in KVM's vms? My thoughts would be adding acpid installation through the XML template, but this would add to the build's size and start up time.

I mention this because as I'm looking into `slim start`, really the only added support for this command would be in VirtualBox unless an unexpected shutdown occurs with KVM.

**Comment by ssmirr** [comment]
do you know _how much_ adding ACPID will impact the image size/start up time?

what do you think about this @chrisparnin?
