### ISSUE TITLE
Add shell completion for images

### ISSUE THREAD

**Issue by gjabell** [ottomatica/slim#8]
Fish/zsh/bash shell completion for images, so that hitting tab with `slim run <name>` will list and auto-complete available images

**Comment by ssmirr** [comment]
The package that we're using for managing commands, [yargs](http://yargs.js.org/docs/#api-completioncmd-description-fn), supports generating completion scripts. But not sure if that would help with this.

**Comment by gjabell** [comment]
Wasn't able to get the `yargs` completion working properly, but I think this isn't a super important task anyways. Can revisit in the future if someone else requests it.
